### ISSUE TITLE
Version 3.0.0 not released to Maven Central

### ISSUE THREAD

**Issue by jgabele** [snowdrop/narayana-spring-boot#133]
Hey all,
is there a reason why the latest version ([3.0.0](https://github.com/snowdrop/narayana-spring-boot/releases/tag/3.0.0)) is not published on 
https://mvnrepository.com/artifact/me.snowdrop/narayana-spring-boot-starter?

We are using the package and would like to update to the latest version, but we can only access 2.6.7.

Thanks for your work!

**Comment by dmbakker** [comment]
They changed me to dev. See: https://mvnrepository.com/artifact/dev.snowdrop/narayana-spring-boot-starter
