### ISSUE TITLE
Error enlisting after update to 3.1.0 in MariaDB and DB2

### ISSUE THREAD

**Issue by oburgosm** [snowdrop/narayana-spring-boot#140]
I have an application that use narayana-spring-boot with JPA and works fine with 3.0.0. After update it to 3.1.0 it begin to fail with MariaDB and DB2, although it runs with Postgres or H2.

I have been investigating the error and looks like the problem is on commit bbadc28087dd8b31e12f533fcf0ac43f7159816a. 

My application has the following property:

narayana.transaction-manager-id=${random.uuid}

Then, like transaction-manager-id has more than 28 bytes, it's replaced with value generated with the new function `shortenNodeIdentifier`. But this cause that MariaDB and DB2 fail starting transaction (enlisting it). In case of MariaDB it throws a SQLSysntaxException.

**Comment by graben** [comment]
@oburgosm: I think this issue can be closed

**Comment by oburgosm** [comment]
Yes, It's solved in 3.1.1 via #141. Thanks!
