### ISSUE TITLE
Periodic Recovery thread of RecoveryManagerService blocks the shutdown gracefully

### ISSUE THREAD

**Issue by ferblaca** [snowdrop/narayana-spring-boot#165]
I am having problem so that the applications of Batch typology (spring-batch) that use XA with Narayana stop in a friendly way when they finish their process.

From what I have been able to see, the problem resides in that when creating the `RecoveryManagerService` bean and performs the `start()`. it ends up creating the thread with name `Periodic Recovery` as **daemon=false**, which prevents the JVM from terminating when it receives a gracefully shutdown when it finishes processing its code from the main.

The only way I have been able to solve the problem is to redefine the `RecoveryManagerService` bean and not perform the `start()`, but I don't like this solution:

```java
  @Bean(destroyMethod = "stop")
  @DependsOn({"narayanaPropertiesInitializer"})
  public RecoveryManagerService recoveryManagerService(CustomNarayanaProperties properties) {
    RecoveryManager.delayRecoveryManagerThread();
    final RecoveryManagerService recoveryManagerService = new RecoveryManagerService();
    recoveryManagerService.create();
    // if properties.getPeriodRecovery().isEnabled()==false do not start the recovery manager service because it creates a non-daemon
    // period-recovery thread that avoids the normal termination of the JVM process daemon=false that in bath applications not permits to
    // finish the application when the main process ends.
    if (properties.getPeriodRecovery().isEnabled()) {
      recoveryManagerService.start();
    }
    return recoveryManagerService;
  }
``` 

I have also tried to set the properties `narayana.periodicRecoveryPeriod`, `narayana.expiryScanInterval` with value `0` but it ends up creating the thread daemon=false.

Is there any way by configuration to create the `Periodic Recovery` thread as daemon=true? or just disable the recovery service?

**Comment by jmfinelli** [comment]
Hi @ferblaca, thanks for you question. Isn't there a way to invoke `RecoveryManagerService.stop()`

> I have also tried to set the properties narayana.periodicRecoveryPeriod, narayana.expiryScanInterval with value 0 but it ends up creating the thread daemon=false.
Is there any way by configuration to create the Periodic Recovery thread as daemon=true? or just disable the recovery service?

I wouldn't touch those properties for achieving what you're looking for. Also, I wouldn't disable the Recovery Manager unless you are fine with broken transactions.

**Comment by ferblaca** [comment]
Hi @jmfinelli ,

correct, in fact those properties have no effect on the creation/setting of the Periodic Recovery thread.

For me, the most appropriate solution would be to be able to set the `Periodic Recovery` thread as daemon=true, but currently it is not possible.

**Comment by jmfinelli** [comment]
AFAIU, you would like to achieve a graceful shutdown. OTOH, if Periodic Recovery is killed without shutting it down properly, I don't think we can call this kind of shutdown "graceful".

**Comment by ferblaca** [comment]
@jmfinelli, the problem in our applications is that Periodic Recovery never finishes shutting down correctly, and therefore neither does the JVM. If at least once past the last interval defined in `periodicRecoveryPeriod` it would shutdown once gracefully shutdown was previously executed it wouldn't be so problematic, but that doesn't happen either.

**Comment by jmfinelli** [comment]
How are you shutting down Periodic Recovery? Do you have any Narayana logs we can review to understand why Periodic Recovery's shutdown isn't completing correctly?

**Comment by graben** [comment]
I wonder how your application is going to shut down. Normally every Spring application is going to destroy its created beans, which is calling stop on recovery service. Periodic recovery normally needs only a few seconds for each round. Maybe you have many broken transactions on your device?

**Comment by ferblaca** [comment]
I will try to reproduce the problem in a simpler application than ours in order to explain it better. If I don't succeed maybe it's something of our applications that I haven't seen yet.

But yes @graben, I see that the stop of the Service Recovery is executed and also the destroy of the beans, but the `Periodic Recovery` thread as daemon=false if alive, so it prevents to turn off the JVM.

If I can reproduce it or not in a simple way I will inform you. Thanks.

**Comment by jmfinelli** [comment]
> Maybe you have many broken transactions on your device?

@graben - AFAIU, even in this case it shouldn't hung (unless @ferblaca is using the new logic to graceful shutdown, i.e. `RecoveryEnvironmentBean.setWaitForWorkLeftToDo(true)`)

**Comment by ferblaca** [comment]
@jmfinelli,

I have created a very simple demo that reproduces the problem at https://github.com/ferblaca/Narayana.

### Steps to reproduce
1. Run the standalone application and verify that the standalone application program never ends.

Check in console log that exists a thread called `Period Recovery` daemon=false.
```
--------------------------> Thread name: Periodic Recovery, Daemon: false
```

To solve this behavior you can set the `recovery.period.start.disabled: true`  which configure a `RecoveryManagerService` Bean without performs the start().

### Point of view
1. Semantics of a batch program (IMHO): A batch program / process runs over a finite amount of time, it must start and end after completing the tasks is meant to do.
2. A batch program cannot run indefinitely, like a web service or a message listener, that wait for client connections "forever".
3. A batch program can need XA/Open distributed transaction semantics among several resources, it's a legitimate use case
4. If the Recovery thread is needed it must be running in a batch (or not batch) program.
5. Current status: If the recovery thread is a non-daemon thread, it will never shutdown even if the "main" thread shuts down, so the batch program will never end; defeating the batch program (finite amount of time running) semantics.
6. If the recovery thread is a daemon thread, by default it will shut down when the main (parent) thread shuts down. But you said that situation will prevent the thread performing needed pre-shutdown tasks to ensure transactions are not broken.
7. If the recovery thread is a daemon thread but the main thread has a waiting time (configurable amount of time) to allow the recovery thread to perform the pre-shutdown tasks; and then finalize the execution, the batch semantics can be honored. I know that you can't always ensure how long the recovery thread will take to perform its tasks; but at least you have a configurable parameter to give it room for it's pre-shutdown tasks.
 
If we are in the situation depicted in point 5, you cannot build a batch program with Narayana because it will be running forever. This given you said the Recovery thread is NEEDED and cannot be inhibited because it could cause having broken transactions.
I think that with (6) and (7) you can keep the Recovery thread doing its work, while allowing to use Narayana for Batch processes that must end.

**Comment by graben** [comment]
You're still using NSB 3.1.1, please try 3.2.0 there have been a lot of fixes and dependency updates.

**Comment by jmfinelli** [comment]
@ferblaca - I tried your reproducer but I'm not sure how to reproduce the problem you're talking about. `PeriodicRecovery.shutdown(boolean)` is invoked and I can see that (dropping a breakpoint [here](https://github.com/jbosstm/narayana/blob/7.0.2.Final/ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java#L179)) the PeriodicRecovery's Thread is not alive. I'm not sure if this can help but I also added `System.out.println("Running something now");` to your `contextLoads` test and it gets printed after `--------------------------> Thread name: Periodic Recovery, Daemon: false`

**Comment by graben** [comment]
@ferblaca : Same for me, program behaves as expected.  Normal run, normal shutdown, no problems occurring.

**Comment by juliojgd** [comment]
I've just run the reproducer from @ferblaca in command line with this setup:
```
09:45 $ mvn -v
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /home/user1/.asdf/installs/ivm-maven/3.9.4
Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: /home/user1/.asdf/installs/ivm-java/openjdk-17.0.12
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

and 
`09:46 $ mvn clean install`

```
[...]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.232 s
[INFO] Finished at: 2024-10-07T09:46:43+02:00
[INFO] ------------------------------------------------------------------------

```
then

`09:46 $ java -jar target/demoBatchNarayana-0.0.1-SNAPSHOT.jar`

and the execution hangs here:
```
[...]
2024-10-07T09:47:15.325+02:00 DEBUG 31804 --- [demoBatchNarayana] [           main] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [INSERT INTO "PRODUCT" ("DISCOUNT", "NAME", "PRICE") VALUES (?, ?, ?)]
2024-10-07T09:47:15.325+02:00  INFO 31804 --- [demoBatchNarayana] [           main] c.e.b.n.d.DemoBatchNarayanaApplication   : product persisted id 10
--------------------------> Thread name: main, Daemon: false
--------------------------> Thread name: Transaction Expired Entry Monitor, Daemon: true
--------------------------> Thread name: Periodic Recovery, Daemon: false
--------------------------> Thread name: Listener:44767, Daemon: true
--------------------------> Thread name: Transaction Reaper, Daemon: true
--------------------------> Thread name: Transaction Reaper Worker 0, Daemon: true
```

The application  does not ever finish. 

If I want to terminate the process I must issue a Ctrl-C (SIGINT) in the terminal. So I find the same problem as @ferblaca found

**Comment by jmfinelli** [comment]
I'm not a Spring developer but I think that this can help:
```
var context = SpringApplication.run(DemoBatchNarayanaApplication.class, args);
addShutdownHook();
SpringApplication.exit(context);
```

**Comment by graben** [comment]
I think you'll need something that will call a shutdown, like SpringApplication.exit(...). Never thought about using Narayana on a self-closing application.

**Comment by ferblaca** [comment]
Thanks @jmfinelli! with this you have given us the clue to ensure that the Shutdown signal reaches the JVM and finally stop the recovery service in an orderly way. Finally we configure de application as:

```java
    public static void main(final String[] args) {
        System.exit(SpringApplication.exit(new SpringApplicationBuilder().sources(Application.class)
            .web(WebApplicationType.NONE).run(args)));
    }
``` 

Regards,

**Comment by jmfinelli** [comment]
@ferblaca Great news! Thanks for sharing it :partying_face:
