### ISSUE TITLE
narayana-spring-boot-3.3.0 fails with SB 3.4.0

### ISSUE THREAD

**Issue by oburgosm** [snowdrop/narayana-spring-boot#173]
I have an application that uses `narayana-spring-boot`. I tried to update this application to spring boot 3.4.0, but it fails with the following message:

```
Caused by: java.lang.NoSuchMethodError: 'void org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers.customize(org.springframework.transaction.PlatformTransactionManager)'
	at dev.snowdrop.boot.narayana.autoconfigure.NarayanaAutoConfiguration.transactionManager(NarayanaAutoConfiguration.java:119)
```

Actually, I don't undestand why it's failing because there is another method with signature : `void org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers.customize(org.springframework.transaction.TransactionManager)`, but I tried to build `narayana-spring-boot-3-3-1-SNAPSHOT` with spring boot 3.4.0 in my local environment and It works fine with my application without erros.

So, It will be nice that `narayana-spring-boot` release a new version that bump to spring boot 3.4.0.

**Comment by graben** [comment]
Already fixed with #172 waiting for release by @jacobdotcosta

**Comment by oburgosm** [comment]
But if you update to SB 3.4.0 there is no need to cast.

**Comment by graben** [comment]
I know but an upgrade to 3.4.x is planned together with the next Camel compatible LTS. So we need something in between for people only using SB.

**Comment by graben** [comment]
@oburgosm: Please try the 3.3.1 release.

**Comment by oburgosm** [comment]
It's works for me. Thanks @graben!
