### ISSUE TITLE
Recovery tests do not pass on JDK 12

### ISSUE THREAD

**Issue by gytis** [snowdrop/narayana-spring-boot#21]
I suspect there to be an issue with Byteman setup which doesn't work on newer JDKs

**Comment by zhfeng** [comment]
@gytis Did you try "-Djdk.attach.allowAttachSelf=true" for the failsafe or the surefire plugins ?
[Configuring BMUnit for the latest JDK9 EA releases](http://bytemanblog.blogspot.com/2017/05/configuring-bmunit-for-latest-jdk9-ea.html)

**Comment by gytis** [comment]
I don't think so. I'll try it out this week

**Comment by gytis** [comment]
Seems to be working fine now. I'm adding it to the CI config
