### ISSUE TITLE
Do not use "spring.*" namespace for configuration properties

### ISSUE THREAD

**Issue by snicoll** [snowdrop/narayana-spring-boot#4]
[Ad described in our documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming), do not use "spring" for [configuration properties](https://github.com/snowdrop/spring-boot-narayana/blob/5dbd499aab94f1444467a892a6308bffccd75235/spring-boot-narayana-core/src/main/java/me/snowdrop/boot/narayana/core/properties/NarayanaProperties.java#L38).

**Comment by gytis** [comment]
@snicoll I've kept the same properties as defined in https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jta/narayana/NarayanaProperties.java#L42 with an idea that the user wouldn't need to change his application when he moves to using this starter from the one which is going to be removed from the Spring Boot repository.
Maybe there is a recommended way of implementing this? E.g creating new properties and using values of the old ones as default?

**Comment by snicoll** [comment]
I understand the rationale but as this is now a 3rd party starter, please follow the recommandations referenced in my description. 

Besides, using the same namespace with two Implementations is asking for trouble IMO.
