### ISSUE TITLE
jbossts-properties.xml found first from narayana-jta-xxx.jar

### ISSUE THREAD

**Issue by graben** [snowdrop/narayana-spring-boot#46]
In some circumstances `jbossts-properties.xml` is first found from narayana-jta-xxx.jar via class loader not from the starter. Since this one is not empty any property set is application.properties is ignored in `NarayanaPropertiesInitializer`.

A valid workaround seems to define empty `jbossts-properties.xml` in the project itself.

**Comment by gytis** [comment]
Interesting. There is an empty properties file defined already https://github.com/snowdrop/narayana-spring-boot/blob/master/narayana-spring-boot-core/src/main/resources/jbossts-properties.xml. Which version failed has failed for you?

**Comment by graben** [comment]
Actually the one from 5.10.6 in narayana-jta-5.10.6.jar

**Comment by gytis** [comment]
@graben when you say that it happens in "some circumstances" what are they? It would make it much easier to track this one down.

**Comment by graben** [comment]
Actually I see this in exploded form of spring boot apps. Maybe it does not occur in fatjar. Have to remote debug it this way.

**Comment by graben** [comment]
Well, it seems to be influenced by the order classloader reads jars.  https://github.com/jbosstm/narayana/blob/1e17caa16b5efb9b16cdb2d8489a1b93722ebdd5/common/classes/com/arjuna/common/util/propertyservice/FileLocator.java#L146

**Comment by gytis** [comment]
Yes, that's probably correct. I'll think of some other workaround.

**Comment by eliasbalasis** [comment]
I think I am suffering from the same symptoms.

Debugging revealls that `jbossts-properties.xml` of `me.snowdrop:narayana-spring-boot-core:2.6.1` is chosen over the expected from `org.jboss.narayana.jta:narayana-jta:5.10.6.Final` but probably after some classpath change which I am still trying to locate.

**Comment by eliasbalasis** [comment]
Further study reveals that, `com.arjuna.common.util.propertyservice.FileLocator` naturally detects presence of `jbossts-properties.xml` on `me.snowdrop:narayana-spring-boot-core:2.6.1` and loads it but after this something else loads the correct configuration from `org.jboss.narayana.jta:narayana-jta`

What could this be?

**Comment by eliasbalasis** [comment]
This has become a blocker for us.

Parent classloading seems to be unpredictably choosing `jbossts-properties.xml` of `me.snowdrop:narayana-spring-boot-core` causing our applications to frequently fail on startup.

Unless you can provide a valid reson for keeping it, I believe it doesn't make sense having an empty `jbossts-properties.xml` on `me.snowdrop:narayana-spring-boot-core` or anywhere else and has to be removed.

**Comment by geoand** [comment]
@Sgitario can you take a look at this please?

**Comment by Sgitario** [comment]
> @Sgitario can you take a look at this please?

I'm not familiar with this project, but will try ...

**Comment by Sgitario** [comment]
@eliasbalasis @geoand https://github.com/snowdrop/narayana-spring-boot/pull/87 can you have a look? I could not find any stopper after removing this file.

**Comment by eliasbalasis** [comment]
This looks good in my view, both the empty properties file and the conflicting environment variables check have been removed.

**Comment by jacobdotcosta** [comment]
This should have been fixed on `2.6.4`.
