### ISSUE TITLE
Release 2.5.0 with Spring Boot 2.3.6 and Narayana 5.10.6

### ISSUE THREAD

**Issue by gytis** [snowdrop/narayana-spring-boot#49]

**Comment by graben** [comment]
@gytis : Shouldn't it be 2.3.4 with Spring Boot 2.2.11 and Narayana 5.10.6?

**Comment by gytis** [comment]
We're keeping a couple of branches for maintenance. master is the one that is the most up to date. 2.3.x branch is aligned with Spring Boot 2.2.x and Narayana 5.9.x (I did the latest release of that yesterday).
I can make a new release from master in a few days.

**Comment by graben** [comment]
Well, 2.3.x and 2.5.x will both be branches based on Spring Boot 2.2.x releases while 2.4.x has Spring Boot 2.3.x? Sound a bit odd, doesn't it?

**Comment by gytis** [comment]
Duh... yes my bad. It should be the latest Spring Boot 2.3.x.
