### ISSUE TITLE
Refactor pool properties handover between starter and core

### ISSUE THREAD

**Issue by graben** [snowdrop/narayana-spring-boot#51]
Actually `NarayanaProperties` is directly handover between starter and core. This makes it difficult to easly create multiple datasources or connection factories with individual configurations. It should be considered to change core API to only transfer `HashMap<String, String>` for `XADataSource`s and `MessagingHubConnectionFactoryProperties` for `XAConnectionFactory`ies.

Maybe a better layout could be developed to unify the usage of pools for jdbc/jms connections.

**Comment by graben** [comment]
@gytis : If you think that's okay I'll build a PR on that.

**Comment by gytis** [comment]
Sure, I don't see an issue with passing a subset of the properties to the different wrappers.

As for the different layout I'm open to suggestions. Just that we should consider deprecating older properties if we'll end up changing the names or prefixes..

**Comment by graben** [comment]
I hope to find a smooth way without breaking the old world ;)
