### ISSUE TITLE
How to use JDBCStore instead of the default FileStore ?

### ISSUE THREAD

**Issue by desprez** [snowdrop/narayana-spring-boot#67]
I would like to use JDBCStore instead of the default FileStore for an application running on Kubernetes using PostgreSQL + JMS.
I wouldn't want to use StateFullSet but rather store the transaction log in the PostgreSQL database. 

I have add this configuation in application.yml file
`narayana:
  dbcp:
    enabled: true
    initialSize: 10
  messaginghub:
    enabled: true
    maxConnections: 10`

and add this jbossts-properties file:

<?xml version="1.0"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
	<entry key="ObjectStoreEnvironmentBean.objectStoreType">com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore</entry>
	<entry key="ObjectStoreEnvironmentBean.jdbcAccess">com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DynamicDataSourceJDBCAccess;ClassName=org.postgresql.ds.PGSimpleDataSource;DatabaseName=sample-service;User=postgres;ServerName=jdbc-object-store;Password=admin</entry>
	<entry key="ObjectStoreEnvironmentBean.tablePrefix">Action</entry>
	<entry key="ObjectStoreEnvironmentBean.dropTable">true</entry>
	<entry key="ObjectStoreEnvironmentBean.stateStore.objectStoreType">com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore</entry>
	<entry key="ObjectStoreEnvironmentBean.stateStore.jdbcAccess">com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DynamicDataSourceJDBCAccess;ClassName=org.postgresql.ds.PGSimpleDataSource;DatabaseName=sample-service;User=postgres;ServerName=jdbc-object-store;Password=admin</entry>
	<entry key="ObjectStoreEnvironmentBean.stateStore.tablePrefix">stateStore</entry>
	<entry key="ObjectStoreEnvironmentBean.stateStore.dropTable">true</entry>
	<entry key="ObjectStoreEnvironmentBean.communicationStore.objectStoreType">com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore</entry>
	<entry key="ObjectStoreEnvironmentBean.communicationStore.jdbcAccess">com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DynamicDataSourceJDBCAccess;ClassName=org.postgresql.ds.PGSimpleDataSource;DatabaseName=sample-service;User=postgres;ServerName=jdbc-object-store;Password=admin</entry>
	<entry key="ObjectStoreEnvironmentBean.communicationStore.tablePrefix">Communication</entry>
	<entry key="ObjectStoreEnvironmentBean.communicationStore.dropTable">true</entry>
</properties>

And this error occurred:
`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1312)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
	... 67 common frames omitted`

I am wondering how to add this JDBCStore configuration ?

**Comment by gytis** [comment]
Could you paste the whole configuration file? Or if you have a reproducer, that would be even better.

**Comment by gytis** [comment]
But looks like you're missing the default Narayana configuration entries. Because you have a dedicated `jbossts-properties` file in your class-path, properties initializer skips the Spring Boot Narayana properties or their default values. Therefore, you need to set them in your `jbossts-properties` file yourself. Here are the default values, that the initializer would set if you wouldn't have had the `jbossts-properties` file:

```
  <entry key="CoreEnvironmentBean.nodeIdentifier">1</entry>
  <entry key="JTAEnvironmentBean.xaRecoveryNodes">1</entry>
  <entry key="ObjectStoreEnvironmentBean.objectStoreDir">transactions-log</entry>
  <entry key="CoordinatorEnvironmentBean.commitOnePhase">YES</entry>
  <entry key="CoordinatorEnvironmentBean.defaultTimeout">60</entry>
  <entry key="RecoveryEnvironmentBean.periodicRecoveryPeriod">120</entry>
  <entry key="RecoveryEnvironmentBean.recoveryBackoffPeriod">10</entry>
  <entry key="JTAEnvironmentBean.xaResourceOrphanFilterClassNames">
      com.arjuna.ats.internal.jta.recovery.arjunacore.JTATransactionLogXAResourceOrphanFilter
      com.arjuna.ats.internal.jta.recovery.arjunacore.JTANodeNameXAResourceOrphanFilter
      com.arjuna.ats.internal.jta.recovery.arjunacore.JTAActionStatusServiceXAResourceOrphanFilter
  </entry>
  <entry key="RecoveryEnvironmentBean.recoveryModuleClassNames">
      com.arjuna.ats.internal.jta.recovery.arjunacore.CommitMarkableResourceRecordRecoveryModule
      com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule
      com.arjuna.ats.internal.txoj.recovery.TORecoveryModule
      com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule
  </entry>
  <entry key="RecoveryEnvironmentBean.expiryScannerClassNames">
      com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner
  </entry>
```

Try adding them in addition to the JDBC object store properties.
