### ISSUE TITLE
Support ordering of XAResource

### ISSUE THREAD

**Issue by apinske** [snowdrop/narayana-spring-boot#85]
The default order of `XAResource`s in this basic sample (https://github.com/apinske/playground-mq/tree/narayana-spring-boot-issues-85) is: ActiveMQ first, H2 second. I think it is undefined what the actual order is. But it seems to be in registration order (MQ first by the listener).
This may lead to a race condition when processing the subsequent message. The MQ message is committed, while the DB TX is not yet committed (although will be, because prepare was successful). It's a small time window. But the Message may then already be consumed by another listener, which would then read old DB data.
Application Servers usually order MQ-Resources after DB-Resources, to mitigate exactly this sort of behaviour. I think JBoss does that too.
But standalone Narayana in Boot does not. Can we please have some sort of ordering when using Narayana in Boot?

**Comment by graben** [comment]
A solution might be once agroal/agroal#69 is solved and released.

**Comment by graben** [comment]
Agroal 2.3 released with new feature first resource.

**Comment by apinske** [comment]
is there any way to get this in the 2.x-line?

**Comment by graben** [comment]
I would suppose no. It's nothing implemented in the Narayana integration.

**Comment by geoand** [comment]
@graben I assume this no longer makes sense?

**Comment by graben** [comment]
@geoand: Me too!

**Comment by geoand** [comment]
🙏🏼
