### ISSUE TITLE
Recovery Manager - Periodic Recovery Failed Connection Recurring issue.

### ISSUE THREAD

**Issue by themulbrook** [snowdrop/narayana-spring-boot#96]
Following the spring-boot-sample-2ds as a template, I have successfully enlisted two PostgreSQL databases to work with narayana. 

In order to test the Recovery Manager, I interrupt a JDBC resource connection and observe the transaction log being written to the object storage. When I wait for the recovery manager to handle this error, I receive an error about establishing connection.

Out of this scenario, two questions come to mind:
1/ what is the proper way to enlist credentials to the Recovery Manager using this starter? I've tried using application.properties and calling  RecoveryCredentialsProperties() in my configuration. 

2/ Am I thinking about the recovery manager correctly in how it operates? Will it replay the transaction logs in object storage? 

3/ If there are two resources in my transaction boundary (similar to spring-boot-sample-2ds) , should I be enlisting both of them to the recovery manager in the case of failure with one in particular?

I appreciate the time spent to answer these questions, it will help me a lot.

**Comment by geoand** [comment]
@graben does this still make sense?

**Comment by graben** [comment]
@geoand: I don't think so. I did a lot of testing with multiple database types successfully.

**Comment by geoand** [comment]
Thanks for checking!
